{
    "entryScript": "score.py",
    "runtime": "python",
    "condaFile": "conda_dependencies.yml",
    "extraDockerfileSteps": null,
    "dependencies": null,
    "enableGpu": false,
    "baseImage": null,
    "baseImageRegistry": null
}